### ISSUE TITLE
Preprocessor

### ISSUE THREAD

**Issue by PavelVozenilek** [delta-lang/delta#60]
Few notes about the preprocessor, mainly based on the short mention in docs.

1. Preprocessor has one very useful property. It runs the first, always. As such, it is easy to think about it, unlike actions done on the source at some unknown point later.

-----------
2.  Docs: _Delta only has the conditional compilation directive #ifdef and its friends, which can be configured only from the command-line, not from source code as can be done in C and C++ with #define._

    This is going in the good direction, but I'd extend it for large scale programs:

       1.  If program is small, then having its defines on cmdline is sufficient.
       2.  However, if the code base gets bigger, it may be inconvenient. Cmdline length has its limitations and it's hard to place cmdline parameters into versioning system.

             My proposal is for such projects to use auxiliary file, with fixed known name (e.g. `configuration.delta`, always in project root, the name being reserved and not allowed for ordinary source). This file would contains all defines for the project and nothing else. If command line still uses any defines, they would apply only to this auxiliary file, not elsewhere. (This means the cmdline defines would be valid only  in `configuration.delta`, and may not be used at all in the ordinary code).

       This arrangement would keep all defines in one, well known and easy to review location.

    A 3rd party library could provide their own `configuration.delta` file, intended to be a hint which specified what macros the library uses. Its content could be manually merged into the project's `configuration.delta` in the project's root. Library's `configuration.delta` would be ignored by the compiler (due to being in "wrong" place).
      
---------------

3.  "Boolean" defines, e.g. `#define FOO` (`-DFOO`), should be always present even if undefined/false.

    ```
     #define FOO // goes the path1 : #ifdef FOO path1 #else path2 #endif

     #undef FOO // goes path2 : #ifdef FOO path1 #else path2 #endif

     ... if FOO is neither defined not undefined, its use means error

    ```

    On cmdline it could be `-DFOO, -UDFOO`, or `-DFOO=false`.

    This would eliminate oversights, when someone forgot something and quietly and unknowingly picked up the `undef` path.

----------------
4. If define is numeric, then it would be helpful to provide range or enumeration for the value:

    ```
    #define FOO_PERCENTS  40 in 0 .. 100
    #define SIZE 1 in 1, 2, 4, 8, 16
    ```

   These numeric constraints would be observed in the code, e.g.   `#if FOO_PERCENTS > 200` would be then refused as completely impossible.

   This would eliminate basic mistakes, using some number while not really knowing what it means.

----------------
5. If define is enumeration of symbols, then all symbols should be present, like:

    ```
    #define PLATFORM WIN in WIN, UNIX, MACOS
    ```

    Use of enumerated define would check against typos, against unknown values and against missing values.  Newly added platform would need the proper update everywhere,  it won't leave some path forgotten.

    All enumerated values should be covered:

    ```
    // this would be OK
   #if PLATFORM == WIN ... #elif PLATFORM == UNIX .... #elif PLATFORM == MACOS .... #endif 
     
   // here compiler would complain about missing path for MACOS
   #if PLATFORM == WIN ... #elif PLATFORM == UNIX .... #endif 
    ```

--------------
6. I use this trick:

    ```
    #ifdef DEBUG
    #  define DBG(...) __VA_ARGS__
    #else
    #  define DBG(...) 
    #endif
    ```

    to have debug only function parameters and values w/o much typing. It is technically macro substitution, but not really. Something like that would be handy.

    C example:
    ```
    // in DEBUG mode function takes additional __FILE__, __LINE__ 
    // parameters for better troubleshooting
    void foo(int x, int y DBG(, const char* file, int line)) { ... }
    ...
    foo(10, 20 DBG(, __FILE__, __LINE__));
    ```

    Ideally, the language would be aware what such trick means, and would NOT require that noisy comma separator:
    ```
    // comma inserted automagically
    void foo(int x, int y DBG(const char* file, int line)) { ... }
    ...
    foo(10, 20 DBG(__FILE__, __LINE__)); // comma inserted automagically
    ```

    or perhaps even would insert "implicit DBG macro":

    ```
    void foo(int x, int y DBG(const char* file, int line)) { ... }
    ...
    foo(10, 20,  __FILE__, __LINE__); // means foo(10, 20) in release
    ```

**Comment by emillaine** [comment]
1. C* will not have a traditional preprocessor like in C and C++. I think it's commonly accepted that the preprocessor as implemented in C and C++, while sometimes very useful, is full of problems.

    Instead, C* will attempt to provide satisfying alternative solutions to most use cases of macros in C and C++.

2. Yes, this kind of build configuration file is a good idea, as demonstrated by most modern languages. C* will have something similar. This is being tracked at: https://trello.com/c/XMcfC7xv/83-build-configuration-file

3. You're right, uses of boolean defines should require them to be explicitly set to true or false, to protect against typos etc. Currently undefined macros are treated as false in `#ifdef` checks. I created the following card to track this: https://trello.com/c/BYrmpGmA/429-warn-about-undefined-macros

4. I'm not sure how useful this would be, `#if FOO_PERCENTS > 200` doesn't seem like something someone would actually write. We will probably come back to this later if it turns out to be useful. Anyway, something similar could be achieved via enums' exhaustiveness-checking, see point 5 below.

5. The plan is to allow using `enum`s and compile-time `switch`-statements' exhaustiveness-checking to address this. Something like:

       switch (os.platform()) {
         case Windows: …
         case Unix: …
       }

    The return type of `os.platform()` would be an enum containing all the possible values, so the compiler would give an error here saying `enum value 'macOS' not handled in switch`. Also, only the branch for the current platform will be compiled, since the return value of `os.platform()` is a known compile-time constant.

    Tracking issue: https://trello.com/c/qXDJPlhM/430-compile-time-switch-and-if

6. Yes, debug-only code is a good idea. The current idea for syntax would be a simple `if (DEBUG) { … }`. I haven't yet thought about debug-only parameters and whether we want to support them and if so, with what kind of syntax. I created a card to track this feature: https://trello.com/c/ywrhEpgN/428-debug-only-code

I'll close this issue and track the specific issues in their own cards. Thanks for the writeup!
